#spring.cloud.vault.kv.application-name=auth-service
#spring.cloud.vault.kv.backend=secret
#spring.cloud.vault.uri=http://127.0.0.1:8200
#spring.cloud.vault.token=${TOKEN_VAULT}
#
## Indiquer à Spring Cloud Vault où trouver le secret
#spring.cloud.vault.generic.secret-backend=secret
#spring.cloud.vault.generic.default-context=auth-service
#
## Permet d'exposer les valeurs de Vault comme propriétés Spring
#spring.cloud.vault.enabled=true
# Activer l'exposition de l'endpoint health
management.endpoint.health.show-details=always

# Configuration du health check pour Consul
spring.cloud.consul.host=server-consul
spring.cloud.consul.port=8500
spring.cloud.consul.discovery.enabled=true
spring.cloud.discovery.enabled=true
spring.cloud.consul.discovery.health-check-path=/actuator/health
spring.cloud.consul.discovery.health-check-interval=10s
spring.cloud.consul.discovery.health-check-timeout=5s
spring.cloud.consul.discovery.prefer-ip-address=true
spring.cloud.consul.discovery.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

management.endpoints.web.exposure.include=*
spring.datasource.url=jdbc:postgresql://moussaadaa-postgres.default.svc.cluster.local:5432/utilisateur-db
spring.datasource.username=moussaadaDB
spring.datasource.password=R3pp6sva
spring.jpa.hibernate.ddl-auto=update
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
